#!/bin/bash
#/home/isucon/work/benchmarker -t http://127.0.0.1/ -u /home/isucon/work/userdata | tee bench-latest/bench.txt
PUBLIC_IP="10.0.1.77"
#ssh admin@52.198.96.21 "~/bench $PUBLIC_IP" | tee bench-latest/bench.txt
#ssh admin@52.197.38.75 "~/bench $PUBLIC_IP" | tee bench-latest/bench.txt
ssh admin@10.0.1.123 "~/bench $PUBLIC_IP" | tee bench-latest/bench.txt

