#!/bin/bash
cd $(dirname $0)
BENCH_DIR=$(pwd)/bench-$(date '+%Y%m%d%H%M%S')
mkdir -p $BENCH_DIR
ln -nfs $BENCH_DIR bench-latest

./restart
sleep 3
dstat -tam --output=$BENCH_DIR/dstat.csv >/dev/null 2>&1 & 
echo $! > dstat.pid
curl http://localhost:6060/startprof
exit 0
